### ISSUE TITLE
DID context URL

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/did-method-key-js#12]
Apparently we should be using 
https://w3id.org/did/v0.11
rather than the not-yet-standardized:
https://www.w3.org/ns/did/v1
The recent changes should be reverted.

@dlongley What story should docs, changelogs, etc have for developers to understand how to deal with this issue and the eventual migration issue?

**Comment by dlongley** [comment]
@davidlehn,

We should link to an explanation for how the contexts are versioned (which should live elsewhere ... probably over at did-core). That explanation, if not already written (I thought @dmitrizagidulin may have written this up in the past already), should indicate that the final URL "https://www.w3.org/ns/did/v1" will be used for the core DID context when the DID core spec reaches REC status, but until then, it should not be used because it is not stable. Use a versioned context instead -- followed by apologies that bleeding edge implementers will just have to deal with shifting sands (several of these URLs) until the standardization process completes.

**Comment by davidlehn** [comment]
Fixed in #13.
